name: Python + Docker CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Docker Buildx (optional but recommended)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Build and start all services
      - name: Build and start Docker Compose services
        run: |
          docker-compose up -d --build
          # Wait a few seconds for MQTT to be ready
          sleep 10

      # 4. Run tests inside mqtt-bridge
      - name: Run mqtt-bridge tests
        run: docker-compose run --rm mqtt-bridge pytest

      # 5. Run tests inside mqtt-publish
      - name: Run mqtt-publish tests
        run: docker-compose run --rm mqtt-publish pytest

      # 6. Tear down
      - name: Stop Docker Compose services
        run: docker-compose down